### ISSUE TITLE
Running the code!

### ISSUE THREAD

**Issue by ben-pr-p** [BrandNewCongress/core#28]
After you've got the code running, leave a 👍 on this comment, or post your error message alongside the commands you ran as a comment.

**Comment by seangtkelley** [comment]
So I successfully setup up all dependencies and the site is running but I'm getting this error:
```sh
[info] JOIN events to Core.EventsChannel
  Transport:  Phoenix.Transports.WebSocket
  Parameters: %{}
[info] Replied events :ok
[error] GenServer #PID<0.512.0> terminating
** (Protocol.UndefinedError) protocol Enumerable not implemented for nil. This protocol is implemented for: DBConnection.PrepareStream, DBConnection.Stream, Date.Range, Ecto.Adapters.SQL.Stream, File.Stream, Flow, Function, GenEvent.Stream, HashDict, HashSet, IO.Stream, List, Map, MapSet, Postgrex.Stream, Range, Stream, Timex.Interval
    (elixir) lib/enum.ex:1: Enumerable.impl_for!/1
    (elixir) lib/enum.ex:116: Enumerable.reduce/3
    (elixir) lib/enum.ex:1832: Enum.map/2
    (core) web/channels/events_channel.ex:19: Core.EventsChannel.handle_in/3
    (phoenix) lib/phoenix/channel/server.ex:226: anonymous fn/4 in Phoenix.Channel.Server.handle_info/2
    (stdlib) gen_server.erl:616: :gen_server.try_dispatch/4
    (stdlib) gen_server.erl:686: :gen_server.handle_msg/6
    (stdlib) proc_lib.erl:247: :proc_lib.init_p_do_apply/3
Last message: %Phoenix.Socket.Message{event: "ready", payload: %{}, ref: "34", topic: "events"}
State: %Phoenix.Socket{assigns: %{}, channel: Core.EventsChannel, channel_pid: #PID<0.512.0>, endpoint: Core.Endpoint, handler: Core.UserSocket, id: nil, joined: true, pubsub_server: Core.PubSub, ref: nil, serializer: Phoenix.Transports.WebSocketSerializer, topic: "events", transport: Phoenix.Transports.WebSocket, transport_name: :websocket, transport_pid: #PID<0.479.0>}
```
The local site seems to be running fine but I wanted to make sure.

OS: Ubuntu 16.04

**Comment by ben-pr-p** [comment]
Ah yeah Sean, this is a problem with our staging NationBuilder – it doesn't have events / calendars formatted in the same way. 

I've created issue #30 to track the fix, but it shouldn't effect development beyond events not showing up on `/events` `/act` or any of the places events pop up
